### ISSUE TITLE
“inference”，“Dataset”

### ISSUE THREAD

**Issue by cherryolg** [EricFH/SOR#5]
Hello, author. I want to apply your model to other test datasets, not ASR. Does your model have any requirements for the test dataset? Do I need to have all the labels of ASR? Looking forward to your reply!

**Comment by EricFH** [comment]
Inference stage does not need label.

**Comment by cherryolg** [comment]
Thank you very much for your reply.&nbsp;I want to make sure what you mean: can I use any dataset I want to use for inference?&nbsp;Just need to include "images" in the dataset, right?Looking forward to&nbsp; your reply again, thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EricFH/SOR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月25日(星期五) 晚上10:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [EricFH/SOR] “inference”，“Dataset” (Issue #5)





 
Inference stage does not need label.

**Comment by cherryolg** [comment]
Hello, author!

For example, my test dataset size is not (480,640). I found that when considering "pos" in the code, i.e., positional coordinate maps, the size was fixed (480,640). And paper says “We take an end-to-end training strategy. The shape of input images is 640 X 480, Which is the same as the original images." Can this model process image whose size is not (480,640)? The actual size may be smaller than (480,640).





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EricFH/SOR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月25日(星期五) 晚上10:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [EricFH/SOR] “inference”，“Dataset” (Issue #5)





 
Inference stage does not need label.

**Comment by EricFH** [comment]
> 

The size is not fixed, every proposal will get the same size after roi pooling no matter what input shape it is. inference stage does not need label. Labels in validate set is for evaluation.

**Comment by cherryolg** [comment]
Thank you very much! Your answer helped me a lot!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EricFH/SOR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月29日(星期二) 中午1:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [EricFH/SOR] “inference”，“Dataset” (Issue #5)





   
The size is not fixed, every proposal will get the same size after roi pooling no matter what input shape it is. inference stage does not need label. Labels in validate set is for evaluation.

**Comment by jiangyuanlin01** [comment]
Can you provide the code of the final results with different colors？
